---
- name: "Déploiement d'une instance ETL (n8n)"
  hosts: docker_hosts
  
  # Ces variables peuvent être surchargées via --extra-vars lors de l'appel du playbook
  vars:
    instance_name: "default_etl"
    host_port: "5678"
    
    # Cible PostgreSQL pour la persistance interne de n8n
    target_db_host: "pg_default"
    target_db_name: "default_db"
    target_db_user: "db_admin"
    target_db_password: "SuperSecretPassword123!"

  roles:
    - role: n8n_instance
